Project/Controllers/AboutController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Project.Models;
using Project.Models.Enums;
using System;
using System.Security.Claims;

namespace Project.Controllers
{
    [Authorize]
    public class AboutController : Controller
    {
        /// <summary>
        /// About Us main page
        /// </summary>
        /// <returns>View</returns>
        public IActionResult Index()
        {
            var userDetail = GetCliams();
            ViewBag.User = userDetail.Name;
            return View();
        }

        /// <summary>
        /// Checking the User Details
        /// </summary>
        /// <returns>{LoggedInDetails} User Details</returns>
        private LoggedInDetails GetCliams()
        {
            LoggedInDetails log = new LoggedInDetails();
            var identity = (ClaimsIdentity)User.Identity;
            var details = identity.Claims;
            foreach (var claim in details)
            {
                switch (claim.Type)
                {
                    case ClaimTypes.Name:
                        log.Name = claim.Value;
                        break;
                    case ClaimTypes.Email:
                        log.EmailId = claim.Value;
                        break;
                    case "Id":
                        log.Id = claim.Value;
                        break;
                    case ClaimTypes.Role:
                        log.Role = (LoginEnum)(Convert.ToInt32(claim.Value));
                        break;
                }
            }
            return log;
        }
    }
}

Project/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Project.DatabaseContext.Services;
using Project.Models;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Project.Controllers
{
    public class LoginController : Controller
    {
        //Login Service
        readonly LoginService _login;
        public LoginController()
        {
            _login = new LoginService();
        }

        /// <summary>
        /// Login View
        /// </summary>
        /// <returns>View</returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Checking the Login Information
        /// </summary>
        /// <param name="model">Username And Password</param>
        /// <returns>View</returns>
        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Index");
            }
            var result = await _login.LoginAccountAsync(model.UserName, model.Password);
            if (!result.Status)
            {
                TempData["Error"] = string.Join("\n", result.Errors);
                return View("Index");
            }
            var userClaims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, result.Result.Name),
                new Claim(ClaimTypes.Email, result.Result.Username),
                new Claim("Id", result.Result.Id),
                new Claim(ClaimTypes.Role, (Convert.ToInt32(result.Result.Role)).ToString())
            };

            var userIdentity = new ClaimsIdentity(userClaims, "UserDetails");
            var userPrincipal = new ClaimsPrincipal(userIdentity);
            await HttpContext.SignInAsync(userPrincipal);

            return RedirectToAction("Index", "Catalogue");
        }

        /// <summary>
        /// Logout User
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync();
            return View("Index");
        }
    }
}

Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Flare eyeware</title>
	<link rel="stylesheet" href="~/lib/bulma/css/bulma.css" />
	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
	<link rel="stylesheet" href="~/css/site.css" />
	 @if (TempData["Error"] != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@TempData["Error"]");
            };
        </script>
    }

</head>
<body>
	<header>
		<div>
			<div class="columns p-0 m-0 has-background-black-ter" style="background-color:red">
				<div class="column is-narrow p-3 is-align-self-center">
					<a style="display: inline-block;" class="is-size-4 has-text-primary-light" asp-controller="Catalogue" asp-action="Index">Flare eyeware</a>
				</div>
				<div class="column is-align-self-center ml-3 is-narrow">
					<a class="has-text-primary-light is-size-5" asp-controller="Catalogue" asp-action="Index">Catalogue</a>
				</div>
				<div class="column is-align-self-center ml-1 is-narrow">
					<a class="has-text-primary-light is-size-5"  asp-controller="About" asp-action="Index">About Us</a>
				</div>
				<div class="column has-text-right is-align-self-center mr-3">

					<span class="has-text-primary-light is-block">@ViewBag.User</span>
					<a asp-controller="Login" asp-action="Logout">Logout</a>
				</div>
			</div>
		</div>
	</header>
	<div class="container">
		<main role="main" class="p-3 mb-5">
			@RenderBody()
		</main>
	</div>
	<footer>
		<div style="width:100%; position:fixed; bottom:0" class="p-1 has-background-grey-light">
			<span class="ml-3 is-block">Designs by Arsh Luthra</span>
		</div>
	</footer>
</body>
</html>

Project/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>

<html style="height:100%">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - Project</title>
    <link rel="stylesheet" href="~/lib/bulma/css/bulma.css" />
    <link rel="stylesheet" href="~/css/custom.css"/>

</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>